#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running pre-push hook: Linting code..."
npm run lint
if [ $? -ne 0 ]; then
  echo "Linting failed. Please fix the errors before pushing."
  exit 1
fi

echo "Linting passed. Proceeding with push."
exit 0 